<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
$config['appid'] = '';
$config['mch_id'] = '';
$config['apikey'] = '';
$config['appsecret'] = '';
$config['sslcertPath'] = APPPATH . 'libraries/wxpay/cert/apiclient_cert.pem';
$config['sslkeyPath'] = APPPATH . 'libraries/wxpay/cert/apiclient_key.pem';
$config['CURL_PROXY_HOST'] = '0.0.0.0';
$config['CURL_PROXY_PORT'] = 0;
$config['REPORT_LEVENL'] = 1;
